### ISSUE TITLE
Add --properties-file option

### ISSUE THREAD

**Issue by neelakansha85** [neelakansha85/mirror_db#3]
Add `--properties-file` option with default value as the `db.properties` file in current mirror_db dir. 
User can use this option to provide a different properties file with a absolute path to the file.

**Comment by bhavin1191** [comment]
Enhancement added on commit number [780c1e3 ](https://github.com/neelakansha85/mirror_db/commit/780c1e321d64c045d4e38332fe502089bd4374fd)
